modLoader = "javafml"
loaderVersion = "*"
license = "All Rights Reserved"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Minestrator"
description = "Integration of Minestrator-hosted servers directly in Minecraft"
logoFile = "assets/minestratorhelper/icon.png"
logoBlur = false

[[dependencies.minestratorhelper]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.minestratorhelper]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"
